### ISSUE TITLE
tkinter not working on Mac

### ISSUE THREAD

**Issue by kasontroy** [Zxynine/AnyMacro#2]
Maybe a larger issue than the plugin?

![image](https://user-images.githubusercontent.com/2547150/166959616-ff88c515-5a38-44f9-9362-29b4e1cdf76d.png)

**Comment by kasontroy** [comment]
The addin doesn't run at all on my Mac. It might be related to an ongoing issue with python, tkinter on Macs. I tried reinstalling f360 hoping that it would rebuild the python framework with 3.10, which is currently on my Mac, but no luck. I even tried installing 3.10 directly into the webdeploy folder, but fusion really didn't like that.

Maybe I'm missing something.

**Comment by Zxynine** [comment]
> Maybe a larger issue than the plugin?
> 
> ![image](https://user-images.githubusercontent.com/2547150/166959616-ff88c515-5a38-44f9-9362-29b4e1cdf76d.png)

Thanks for letting me know! This may just be an oversight on my part assuming that all python versions/fusion come with TK inter as mine did and I have not heard any other issues about this. For now, you can solve this by just following:

For Python3 tkinter can be simply installed by,

`brew install python-tk`
pip sometimes wont work successfully on my Mac, especially with the High Sierra OS version. Brew can be used to install all kinds of software packages in mac.

**Comment by Zxynine** [comment]
Though its weird, because if i recall correctly, TK inter is what they use on windows to display popups, so they may use something else for mac

**Comment by kasontroy** [comment]
I think they run a virtual python instance cuz sys.version says it is 3.9.9, but my machine is running 3.10.4. Also, tkinter shows  the generic window when I run it from terminal.

![image](https://user-images.githubusercontent.com/2547150/166993697-f16daac3-9279-4886-9649-abd83f996138.png)

Even weirder is that the build refers to the correct python.

![image](https://user-images.githubusercontent.com/2547150/167001984-210b6129-31fd-4f26-88ef-779f9cafcd7b.png)

So I dunno 🤷🏽‍♂️

**Comment by Zxynine** [comment]
> I think they run a virtual python instance cuz sys.version says it is 3.9.9, but my machine is running 3.10.4. Also, tkinter shows the generic window when I run it from terminal.
> 
> ![image](https://user-images.githubusercontent.com/2547150/166993697-f16daac3-9279-4886-9649-abd83f996138.png)
> 
> Even weirder is that the build refers to the correct python.
> 
> ![image](https://user-images.githubusercontent.com/2547150/167001984-210b6129-31fd-4f26-88ef-779f9cafcd7b.png)
> 
> So I dunno 🤷🏽‍♂️

You are in luck, I dont actually ever use TK inter, I was doing some tests with it, I had one function which allowed you to copy stuff to your clipboard, but nothing was used. Check the Repo here, go to AddinLib>Util.py and replace the old one with this one that has the right lines commented out, and that should fix your issue.

**Comment by kasontroy** [comment]
IIIIIIIIIIIIII am kicking myself for not trying that first. That resolves the issue. Thanks!
